implementations/implementations.md
Link to Planet's OpenAPI render.
=> Added Planet

.gitignore, demo/LICENSE, demo/README.md, demo/api/main.py, demo/requirements.txt, demo/scripts/run
@jasongilman and I set up a mock FastAPI app to get some scaffolding in place before the sprint.
=> Initial scaffolding for demo API

demo/app/next.config.js, demo/app/package.json, demo/app/src/components/Map/Map.js, demo/app/src/context/appContext.js, demo/app/src/hooks/useApiRequest.js, demo/app/yarn.lock
Also adds frontend proxy config to resolve CORS errors
=> Initial frontend results state and POST request

community-sprints/sprint2-philly/backend_notes.md, demo/api/api_types.py, demo/api/backends/__init__.py, demo/api/backends/base.py, demo/api/backends/fake_backend.py, demo/api/backends/planet_backend.py, demo/api/backends/sentinel_backend.py, demo/api/main.py, demo/api/tests/test_api.py
This adds the types but doesn't yet change the name to add Product and Opportunity
=> Adding initial types

demo/app/src/components/Header/Header.js, demo/app/src/components/Map/Map.js, demo/app/src/context/appContext.js, demo/app/src/hooks/useApiRequest.js, demo/app/src/pages/index.js
Sets up display conditional for loading spinner and sidebar
=> Update context state for results

demo/api/api_types.py, demo/api/backends/__init__.py, demo/api/backends/base.py, demo/api/backends/fake_backend.py, demo/api/backends/sentinel_backend.py, demo/api/main.py, demo/api/tests/test_api.py
Separate out input and output type (makes things not work)
=> Different input and output types

examples/tasking-api/products.json
Align the product example with the descriptions provided in the product spec readme.
=> fixed product example json to align with description readme

demo/api/api_types.py, demo/api/main.py
Should not require any changes to backend implementations
=> Add `/products/id/opportunities` endpoint

stat.yaml
Draft OpenAPI, without Opportunities yet
Rendered version: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/m-mohr/stat-api-spec/openapi-basics/stat.yaml
=> Added basic OpenAPI file

examples/ProductCollectionPlanet.json
=> Planet product examples

examples/ProductCollectionEusi.json
Adding an example for an EUSI Product Collection
=> Eusi product example

product/README.md
Make it only a JSON Schema
Clarify its the JSON Schema for Opportunity and Order filter field
=> Merge parameters and constraints

README.md, opportunity/README.md, product/README.md
- Clarify conformance classes
- Add conformance classes for GeoJSON geometry types
=> Clarify conformance classes and add conf classes for GeoJSON geom types

opportunity/README.md
This discussion has come up a few times. I think we lean towards saying "if it's an opporunity, you can order it" - if we agree on this, we can fix it here.
=> Define Opportunities as Orderables

product/examples/ProductCollectionEusi.json
remove stub conforms, remove unnecessary parameter from required
=> EUSI Product update

order/README.md
=> #117 changed datetime field

opportunity/README.md, opportunity/examples/umbra/OpportunityResponseUmbra.json
=> Add rel=order refs and tweak Opportunity model

core/examples/landingpage.json
=> Update landingpage example #92

product/README.md
=> Allow additional key/value field in products #157

README.md, order/README.md, stat.yaml
Fixes #26 and recent discussions about the orders endpoint
=> Order endpoint clarifications #26

.github/workflows/deploy.yml, .gitignore, package.json
Should deploy to https://Element84.github.io/stat-api-spec/dev
May need some repo setting updates.
=> Create API docs on GH pages

README.md
=> Describe how pagination works #183

.gitignore, README.md, examples/OpportunityCollectionV2.json, examples/OpportunityRequestV2.json, examples/Order.json, openapi.yaml, opportunity/README.md, opportunity/examples/eusi/OpportunityCollectionResponseEusi.json, opportunity/examples/eusi/OpportunityRequestEusi.json, opportunity/examples/planet/OpportunityRequestPlanetAssured.json, opportunity/examples/planet/OpportunityRequestPlanetFlexibleArea.json, opportunity/examples/planet/OpportunityRequestPlanetFlexiblePoint.json, opportunity/examples/planet/OpportunityResponsePlanetAssured.json, opportunity/examples/planet/OpportunityResponsePlanetFlexibleArea.json, opportunity/examples/planet/OpportunityResponsePlanetFlexiblePoint.json, opportunity/examples/umbra/OpportunityRequestUmbra.json, opportunity/examples/umbra/OpportunityResponseUmbra.json, order/README.md
=> Moves product id from request body to path parameters for relevant endpoints. Updates Examples.

README.md, order/README.md, product/README.md
Closes #203 
Improves definition of Product and the intent of this API in the top level README.
=> Update README with what is this api/what is product?

README.md, opportunity/README.md, order/README.md
=> Async opportunity search support

opportunity/README.md, order/README.md
=> Remove requirement to support geometry json refs

opportunity/README.md
=> Add nuance to the description of opportunity create-order links

README.md, opportunity/README.md
Updated top-level README with description of the overall STAPI spec, and the Opportunities README to better describe what an Opportunity is.
=> Updated README files

api-spec.md
=> Fix bad conformance URI for LineString
